name: yarn
on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  autoupdate-lockfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - uses: cachix/install-nix-action@v16
      - run: nix run .#packages.x86_64-linux.updateFrontendDeps
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update yarn.nix
