name: yarn
on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  autoupdate-lockfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - uses: actions/checkout@v3
        if: github.ref != 'refs/heads/main'
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          # pull_request_target checks out the base branch by default
          ref: refs/pull/${{ github.event.pull_request.number }}
      - uses: cachix/install-nix-action@v16
      - run: nix run .#packages.x86_64-linux.updateFrontendDeps
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update yarn.nix
